create type roles as enum('ADMIN', 'MANAGER', 'COURIER', 'CLIENT');
create type statuses as enum('Created', 'Approving', 'Delivering', 'Delivered to pickup point', 'Completed');

create table phones (
    id integer generated by default as identity primary key,
    model varchar(30) not null,
    brand varchar(15) not null,
    stock integer not null
);

create table points (
    id integer generated by default as identity primary key,
    city varchar(30) not null,
    street varchar(50) not null,
    building varchar(15) not null,
    apartment varchar(15) not null
);

create table users (
    id integer generated by default as identity primary key,
    login varchar(30) not null,
    password varchar(255) not null,
    salt varchar(1024) not null,
    surname varchar(100) not null,
    name varchar(100) not null,
    contact varchar(100) not null,
    role roles,
    point_id integer references points(id) default null
);

create table orders (
    id integer generated by default as identity primary key,
    user_id integer references users(id),
    manager_id integer references users(id),
    courier_id integer references users(id),
    point_id integer references points(id),
    phone_id integer references phones(id),
    quantity integer not null,
    status statuses
);

